# Generated by Django 3.2.18 on 2023-07-22 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('shortcode', models.CharField(default='', max_length=20)),
                ('productname', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('barcode', models.CharField(default='', max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.productcategory')),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.CharField(default='', max_length=100)),
                ('unit', models.CharField(default='pc', max_length=50)),
            ],
            options={
                'db_table': 'tblProduct',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('shortcode', models.CharField(max_length=10)),
                ('categoryname', models.CharField(max_length=50, unique=True)),
                ('isactive', models.BooleanField(default=True)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tblProductCategory',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stockid', models.AutoField(primary_key=True, serialize=False)),
                ('threshold', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('discountprice', models.FloatField(default=0)),
                ('stock', models.FloatField(default=0)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.product')),
                ('store', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.store')),
            ],
            options={
                'db_table': 'tblProductStock',
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('historyid', models.AutoField(primary_key=True, serialize=False)),
                ('oldvalue', models.CharField(default='', max_length=50)),
                ('newvalue', models.CharField(default='', max_length=50)),
                ('remarks', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.product')),
                ('stock', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.stock')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblProductStockHistory',
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('historyid', models.AutoField(primary_key=True, serialize=False)),
                ('oldvalue', models.CharField(default='', max_length=50)),
                ('newvalue', models.CharField(default='', max_length=50)),
                ('remarks', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.product')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblProductHistory',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryHistory',
            fields=[
                ('historyid', models.AutoField(primary_key=True, serialize=False)),
                ('oldvalue', models.CharField(default='', max_length=50)),
                ('newvalue', models.CharField(default='', max_length=50)),
                ('remarks', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.productcategory')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblProductCategoryHistory',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.productcategory'),
        ),
    ]
