# Generated by Django 3.2.18 on 2023-07-24 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('invoiceno', models.CharField(default='', max_length=100, unique=True)),
                ('referenceno', models.CharField(default='', max_length=100, unique=True)),
                ('customername', models.CharField(max_length=100)),
                ('customeraddress', models.CharField(max_length=250)),
                ('customertin', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
                ('totalamount', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.store')),
            ],
            options={
                'db_table': 'tblOrder',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(default=0)),
                ('amounttendered', models.FloatField(default=0)),
                ('Order', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.order')),
            ],
            options={
                'db_table': 'tblOrderPayment',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderitemid', models.AutoField(primary_key=True, serialize=False)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.FloatField(default=0)),
                ('unitprice', models.FloatField(default=0)),
                ('order', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.order')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.product')),
            ],
            options={
                'db_table': 'tblOrderItem',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('historyid', models.AutoField(primary_key=True, serialize=False)),
                ('oldvalue', models.CharField(default='', max_length=50)),
                ('newvalue', models.CharField(default='', max_length=50)),
                ('remarks', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.order')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblorderhistory',
            },
        ),
    ]
