# Generated by Django 3.2.18 on 2023-07-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_amounttendered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='orderstatus',
        ),
    ]
