# Generated by Django 3.2.18 on 2023-07-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_status_order_orderstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderstatus',
            new_name='paymentstatus',
        ),
    ]
