# Generated by Django 3.2.18 on 2023-07-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_orderstatus_order_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderstatus',
            field=models.IntegerField(default=0),
        ),
    ]
