# Generated by Django 3.2.18 on 2023-07-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_orderstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='amounttendered',
        ),
    ]
