# Generated by Django 3.2.18 on 2023-07-29 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderitem_amounttendered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
