# Generated by Django 3.2.18 on 2023-07-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customeraddress',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='customername',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='customertin',
            field=models.CharField(default='', max_length=20),
        ),
    ]
